CREATE TABLE STORAGE_(
STORAGE_ID NUMBER NOT NULL PRIMARY KEY,
FORMAT_SUPPORTED NVARCHAR2(100),
COUNTRY_STORAGE NVARCHAR2(50) NOT NULL,
SIZE_STORAGE NUMBER NOT NULL
);

CREATE TABLE FILE_(
FILE_ID NUMBER NOT NULL PRIMARY KEY,
STORAGE_ID NUMBER DEFAULT NULL,
CONSTRAINT STORAGE_FK FOREIGN KEY(STORAGE_ID)REFERENCES STORAGE_(STORAGE_ID),
NAME_FILE NVARCHAR2(20) NOT NULL,
FORMAT_FILE NVARCHAR2(10) NOT NULL,
SIZE_FILE NUMBER NOT NULL
);
