CREATE TABLE HOTEL(
ID NUMBER NOT NULL PRIMARY KEY,
NAME NVARCHAR2(20) NOT NULL,
COUNTRY NVARCHAR2(20) NOT NULL,
CITY NVARCHAR2(20) NOT NULL,
STREET NVARCHAR2(20) NOT NULL
);

CREATE SEQUENCE HOTEL_SEQ MINVALUE 1 MAXVALUE 1000 START WITH 1 INCREMENT BY 1;