CREATE TABLE ROOM(
ID NUMBER NOT NULL PRIMARY KEY,
ID_HOTEL NUMBER,
CONSTRAINT ROOM_FK FOREIGN KEY(ID_HOTEL)REFERENCES HOTEL(ID) ON DELETE SET NULL,
NUMBER_OF_GUESTS NUMBER NOT NULL,
PRICE NUMBER(*, 2) NOT NULL,
BREAKFAST_INCLUDED NUMBER CHECK (BREAKFAST_INCLUDED = 1 OR BREAKFAST_INCLUDED = 0),
PETS_ALLOWED NUMBER CHECK (PETS_ALLOWED = 1 OR PETS_ALLOWED = 0),
DATE_AVAILABLE_FROM TIMESTAMP NOT NULL
);

CREATE SEQUENCE ROOM_SEQ MINVALUE 1 MAXVALUE 1000 START WITH 1 INCREMENT BY 1;