CREATE TABLE ORDER_(
ID NUMBER NOT NULL PRIMARY KEY,
ID_USER NUMBER,
CONSTRAINT ORDER_USER_FK FOREIGN KEY(ID_USER)REFERENCES USER_(ID),
ID_ROOM NUMBER,
CONSTRAINT ORDER_ROOM_FK FOREIGN KEY(ID_ROOM)REFERENCES ROOM(ID),
DATE_FROM TIMESTAMP,
DATE_TO TIMESTAMP,
MONEY_PAID NUMBER(*,2)
);

CREATE SEQUENCE ORDER_SEQ MINVALUE 1 MAXVALUE 1000 START WITH 1 INCREMENT BY 1;